data:
    train: /data/ssedhain/datasets/movielens/1M/90folds/train.flipped.1
    test: /data/ssedhain/datasets/movielens/1M/90folds/test.flipped.1
    save: /data/ssedhain/datasets/movielens/1M/models/autoencoder/new/model.1
params:
    reg_bias: True
    lamda: 0.1
    learn_rate: 0.1
    max_iter: 200
    batch_size: 500
    k : 5
layers:
    1:
        activation: sigmoid
        num_nodes: 30200
        partial: True
        type: input
    2:
        activation: sigmoid
        num_nodes: 500
        partial: False
        type: hidden
        binary: True